<a href="https://colab.research.google.com/github/gabrielcn/Data-Science/blob/main/python_data_science_e_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Verificando a versão do python**

In [1]:
!python -V

Python 3.7.13


**1.3 Trabalhando com arrays numpy**

In [2]:
import numpy as np #Importar a biblioteca numpy

In [3]:
km = np.loadtxt('carros-km.txt') #carrega o arquivo txt dentro de um array numpy

In [4]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [5]:
anos = np.loadtxt('carros-anos.txt', dtype = int) #carrega o arquivo txt dentro de um array numpy e o dtype = int define que a variável "anos" é do tipo inteiro

In [6]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

**Obtendo a quilometragem média por ano**

In [7]:
km_media = km / (2022 - anos)

In [8]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [9]:
type(km_media) #Verifica o tipo da variável, no caso a variável é do tipo numpy.ndarray

numpy.ndarray

**2. CARACTERÍSICAS BÁSICAS DA LINGUAGEM**

**2.1 Operações matemáticas**
    
    Operadores aritméticos: +, -, *, /, **, %, //

**Adição (+)**

In [10]:
2 + 2

4

**Subtração (-)**

In [11]:
2 - 2

0

**Multiplicação (*)**

In [12]:
2 * 2

4

**Divisão (/) e (//)**

A operação divisão sempre retorna um número de ponto flutuante

In [13]:
10 / 3

3.3333333333333335

In [14]:
10 // 3 #Retorna somente a parte inteira da divisão

3

**Exponenciação (****)

In [15]:
2 ** 3

8

**Resto da divisão (%)**

In [16]:
10 % 3

1

**Expressões matemáticas**

In [17]:
5 * 2 + 3 * 2

16

In [18]:
(5 * 2) + (3 * 2)

16

In [19]:
5 * (2 + 3) * 2

50

**A variável**

No modo interativo, o último resultado impresso é atribuído a variável _

In [20]:
5 * 2

10

In [21]:
_ + 3 * 2

16

In [22]:
_ / 2

8.0

**2.2 Variáveis**

**Nomes de variáveis**

° Nomes de varáveis podem começar com letras (a - z, A - Z) ou o caractere underscore (_):

Altura

_peso

° O restante de nome pode conter letras, números e o caractere "_":

nome_da_variavel

_valor

dia_28_11_

° Os nomes são case sensitive:

Nome_Da_Variavel ≠ nome_da_variavel ≠ NOME_DA_VARIAVEL

### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 



### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [23]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0

In [24]:
ano_atual

2022

In [25]:
ano_fabricacao

2003

In [26]:
km_total

44410.0

**Operações com variáveis**

```
# Isto está formatado como código
```




# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$


In [27]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2337.3684210526317

In [28]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total = km_total + km_media
km_total

46747.36842105263

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [29]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0

In [30]:
ano_atual

2022

In [31]:
ano_fabricacao

2003

In [32]:
km_total

44410.0

In [33]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2337.3684210526317

**2.3 Tipos de dados**

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**

    1. **int** - inteiros
        
      **float** - Ponto flutuante

  **° Booleanos** - Assume os valores True ou False. Essencial quando comerçarmos a trabalhar com declarações condicionais


  **° Strings** - Sequencia de um ou mais caracteres que pode inclui letras, números e outros tipos de caracteres. Representa um texto.


  **° None** - Representa a ausencia de valor



**Números**

In [38]:
ano_atual = 2022

In [39]:
type(ano_atual) #função type, que passamos como argumento a variável e ele retorna que tipo de variável é

int

In [40]:
km_total = 44410.0

In [42]:
type(km_total)

float

**Booleanos**

In [43]:
zero_km = True

In [44]:
type(zero_km)

bool

In [45]:
zero_km = False

In [46]:
type(zero_km)

bool

**Strings**

In [50]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [51]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [52]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [53]:
nome = "Jetta 'Variant'"
nome

"Jetta 'Variant'"

In [54]:
carro = '''
Nome
Idade
Nota
'''

In [56]:
carro

'\nNome\nIdade\nNota\n'

In [57]:
type(carro)

str

**None**

In [58]:
quilometragem = None
quilometragem

In [59]:
type(quilometragem)

NoneType

**2.4 Conversão de tipos**

In [60]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [61]:
type(a)

int

In [62]:
type(b)

int

In [63]:
type(c)

str

In [64]:
type(d)

str

In [65]:
c+d

'Python é legal'

In [66]:
#c + a 

TypeError: ignored

**Conversões de tipo**

Funções int(), float(), str()

In [73]:
str(a) #Transforma uma variável que não é do tipo str em uma string

'10'

In [74]:
type(str(a))

str

In [75]:
c + str(a)

'Python é 10'

In [76]:
float(a)

10.0

In [77]:
type(float(a))

float

In [78]:
var = 3.141592

In [79]:
type(var)

float

In [80]:
int(var)

3

In [81]:
var = 3.99

In [82]:
int(var)

3

**Concatenando strings**

In [83]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [87]:
text + str( int( Km / (Ano_atual - Ano_fabricacao) ) ) + ' km' # foram realizadas duas conversões. Na primeira, o resultado da operação (float) é convertido em um inteiro (int) e depois, o dado do tipo inteiro é convertido em uma string (str).

'A quilometragem média do veículo é 5000 km'

**2.5 Indentação, comentários e formatação de strings**


**Indentação**

Na linguagem Python os programas são estrturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [88]:
ano_atual = 2022
ano_fabricacao = 2022

if (ano_atual == ano_fabricacao):
  print('Verdadeiro')
else:
  print('Falso')

Verdadeiro


In [89]:
# Atalho para comentar Ctrl + ;

**Formatação de strings**

**str.format()**

In [91]:
print('Olá, {}!'.format('Gabriel')) #Na chave entra o parametro que está sendo passado para o .format, que no caso é 'Gabriel', substitui {} pelo o que tem no .format

Olá, Gabriel!


In [92]:
print('Olá, {}! Este é seu acesso de número {}'.format('Gabriel', 21))

Olá, Gabriel! Este é seu acesso de número 21


In [94]:
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(nome = 'Gabriel', acessos = 47))

Olá, Gabriel! Este é seu acesso de número 47


**f-Strings**

In [95]:
nome = 'Gabriel'
acessos = 47

In [98]:
print(f'Olá, {nome}! Este é seu acesso de número {acessos}') #Usando o f-Strings, basta só colocar o f na frente

Olá, Gabriel! Este é seu acesso de número 47
